#!/usr/bin/python
from bunch import Bunch, _
import sys

Bunch.connect()

cmd = ' '.join( sys.argv[1:])
src = _( cmd )
print '>>>>>>>>>>>>>>>>>>\r\n', cmd
res = src.execute()
print '<<<<<<<<<<<<<<<<<<\r\n', res.ls()
