#!/usr/bin/python
from bunch import Bunch, _
import sys

Bunch.connect()

cmd = ' '.join( sys.argv[1:])

src = _( cmd )

res = src.execute()

if isinstance( res, Bunch ):
    print res.ls()
else:
    print res
